# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snippr < Formula
  desc ""
  homepage ""
  version "0.5.5"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/snippr-io/homebrew-cli/releases/download/0.5.5/snippr-darwin-amd64.tar.gz"
      sha256 "694b17c64393383efd851abb9a22a6735883c61e5f130dc54b3f34ccb9246cab"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/snippr-io/homebrew-cli/releases/download/0.5.5/snippr-linux-amd64.tar.gz"
      sha256 "a8b8f5684f6c95f8c0830ee9870509fce4625215e189ab700878216ca0cf32ce"
    end
  end

  def install
    bin.install "snippr"
  end
end
